sudo: false
language: python
env:
  global:
  - HELM_VERSION="v2.8.2"
  - KUBEVAL_VERSION="0.13.0"
  - CONFTEST_VERSION="0.15.0"
  - secure: "TE331nSnqb4tczJZSnQePkl4OT6wkL3RmW693t16vyCHGbZL/PPLR28j1o5PSYzs430daRfg54LrsOGAlBXGUgm5wXYXEgXK0FTHKmAjUrervsnsSPHjuCogAPQt71kswpQcBf7c9i3Cg9ek0b4MIGFlEe1XxlSsOQlF97JQMwsha1eCl5DSlw0fTUqJspy+vgCN9rBN9ktk4K0X/yB77TB2Qc8DuNfbMpgjhv3A8+a0jIJw2ui4PcIaZjhwPrAkYqmQKNeAdbpO9NQ9rA71oKU5wiGBEUJxwp170c5EyNc6povmkO9zPDJU485a2Fi/rPOJFrH9WJTyOy8bWBThYBrqPxSS4EOVoe4xDfXtk633Q5MiYwuDjGP8j/H3sG8G/uyieDD+PjWiTJUoaHSWoJ6r++Vt1AAa32Ah/lEq5oITgqLUgh9zcElr1DY7sM5AGe63cPQl0SBcxEsyNLlTkJmd2fxUPW6EYbk5XMI6wjp9R9mYwTdUv+EECqpTPYhpe9obppsJLe0JdBD46X8M3plI0GkhEeep2ohQlYE/UT9fcCnd3OlrZC/XI40yVZKm/TQ6gKiZCbD0VIzcXmeGW15VWtPSSPVLGzzb3BB4E4kEcY8zz7CJrFMI244ZJ375KcuakmRuNKJgI/Zxvum/Kbktz0LxQ04dYEWOTN3+70g="


before_script:
- pip install yq jsonschema pyyaml
- wget "https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz"
- tar zxf helm-${HELM_VERSION}-linux-amd64.tar.gz
- mkdir bin
- mv linux-amd64/helm ./bin/helm
- wget "https://github.com/instrumenta/kubeval/releases/download/${KUBEVAL_VERSION}/kubeval-linux-amd64.tar.gz"
- tar zxf kubeval-linux-amd64.tar.gz
- mv kubeval ./bin/
- wget "https://github.com/instrumenta/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz"
- tar zxf conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz
- mv conftest ./bin/
- export PATH=$PATH:$PWD/bin/
script:
- "./build/update-chart-repo.sh"
after_success:
- "./build/push.sh"
